# Generated by Django 2.0.13 on 2019-03-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_owner', models.CharField(max_length=265)),
                ('address', models.CharField(max_length=255)),
                ('rent', models.PositiveIntegerField()),
                ('house_details', models.TextField()),
                ('rooms', models.PositiveIntegerField()),
                ('students', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
            ],
        ),
    ]
