# Generated by Django 2.0.13 on 2019-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='gender',
            field=models.CharField(choices=[('0', 'Apartment'), ('1', 'Full House'), ('2', 'Rooms')], default='Rooms', max_length=20),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='space_type',
            field=models.CharField(choices=[('0', 'Shared Room'), ('1', 'Private Room'), ('2', 'Entire Space')], default='Shared Room', max_length=20),
        ),
    ]
