# Generated by Django 2.0.13 on 2019-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20190304_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='property',
            field=models.CharField(choices=[('0', 'Apartment'), ('1', 'Full House'), ('2', 'Rooms')], default='Rooms', max_length=20),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Both')], default='Male', max_length=20),
        ),
    ]
