# Generated by Django 2.0.13 on 2019-03-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20190304_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemodel',
            old_name='property',
            new_name='property_choice',
        ),
    ]
