# Generated by Django 2.0.13 on 2019-03-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20190307_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='user',
        ),
    ]
