# Generated by Django 2.0.13 on 2019-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20190304_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Both')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='property_choice',
            field=models.CharField(choices=[('0', 'Apartment'), ('1', 'Full House'), ('2', 'Rooms')], default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='space_type',
            field=models.CharField(choices=[('0', 'Shared Room'), ('1', 'Private Room'), ('2', 'Entire Space')], default='0', max_length=20),
        ),
    ]
