# Generated by Django 2.0.13 on 2019-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20190304_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('B', 'Both')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='property_choice',
            field=models.CharField(choices=[('A', 'Apartment'), ('FH', 'Full House'), ('R', 'Rooms')], default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='space_type',
            field=models.CharField(choices=[('SR', 'Shared Room'), ('PR', 'Private Room'), ('ES', 'Entire Space')], default='0', max_length=20),
        ),
    ]
