# Generated by Django 2.0.13 on 2019-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20190304_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='house_pic',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
