# Generated by Django 2.0.13 on 2019-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_housemodel_house_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='house_pic',
            field=models.ImageField(default='pexels-photo-670061.jpeg', upload_to='media'),
        ),
    ]
