# Generated by Django 2.0.13 on 2019-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20190305_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='house_pic',
            field=models.ImageField(blank=True, upload_to='houses'),
        ),
    ]
