# Generated by Django 2.0.13 on 2019-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20190305_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='house_pic',
            field=models.ImageField(blank=True, default=None, upload_to='houses'),
        ),
    ]
