# Generated by Django 2.0.13 on 2019-03-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_auto_20190305_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='house_pic',
        ),
    ]
